#!/usr/bin/env python3
"""
Generate today's trade memo chart (2026-06-23)
"""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from datetime import datetime
import numpy as np

# Trade data for 2026-06-23
trades = [
    {'symbol': '4141', 'qty': 17, 'entry': 20.94, 'entry_time': '12:36', 
     'exit': 20.94, 'exit_time': '14:30', 'trigger': 'pick_entry', 'peak': 21.19, 'pnl': -0.42},
    {'symbol': '8310', 'qty': 24, 'entry': 7.08, 'entry_time': '13:37', 
     'exit': 7.08, 'exit_time': '14:50', 'trigger': 'vwap_reclaim', 'peak': 7.09, 'pnl': -0.18},
    {'symbol': '9404', 'qty': 17, 'entry': 10.45, 'entry_time': '14:23', 
     'exit': 10.45, 'exit_time': '14:30', 'trigger': 'vwap_reclaim', 'peak': 10.45, 'pnl': -0.20},
]

# Create figure
fig, ax = plt.subplots(figsize=(14, 8))
fig.patch.set_facecolor('#1a1a2e')
ax.set_facecolor('#1a1a2e')

# Title
ax.text(0.5, 0.95, '🪼 TASI Trade Memo — 2026-06-23', 
        transform=ax.transAxes, fontsize=20, fontweight='bold',
        color='#e0e0e0', ha='center', va='top')

# Subtitle
ax.text(0.5, 0.90, 'Market: TRENDING | Session PnL: -0.80 SAR (-0.11%) | Final Capital: 1,030.25 SAR',
        transform=ax.transAxes, fontsize=12, color='#a0a0a0', ha='center', va='top')

# Table headers
headers = ['Symbol', 'Qty', 'Entry', 'Exit', 'Peak', 'PnL', 'Trigger', 'Time In']
header_y = 0.82

# Draw headers
for i, h in enumerate(headers):
    x = 0.08 + i * 0.12
    ax.text(x, header_y, h, transform=ax.transAxes, fontsize=11, 
            fontweight='bold', color='#e0e0e0', ha='center')

# Draw separator line
ax.plot([0.05, 0.95], [header_y - 0.03, header_y - 0.03], 
        transform=ax.transAxes, color='#404060', linewidth=1)

# Draw trade rows
row_y = header_y - 0.08
for trade in trades:
    # Symbol
    ax.text(0.08, row_y, trade['symbol'], transform=ax.transAxes, 
            fontsize=12, color='#e0e0e0', ha='center', fontweight='bold')
    
    # Qty
    ax.text(0.20, row_y, str(trade['qty']), transform=ax.transAxes, 
            fontsize=11, color='#e0e0e0', ha='center')
    
    # Entry
    ax.text(0.32, row_y, f"{trade['entry']:.2f}", transform=ax.transAxes, 
            fontsize=11, color='#4CAF50', ha='center')
    
    # Exit
    exit_color = '#4CAF50' if trade['exit'] >= trade['entry'] else '#f44336'
    ax.text(0.44, row_y, f"{trade['exit']:.2f}", transform=ax.transAxes, 
            fontsize=11, color=exit_color, ha='center')
    
    # Peak
    ax.text(0.56, row_y, f"{trade['peak']:.2f}", transform=ax.transAxes, 
            fontsize=11, color='#FFD700', ha='center')
    
    # PnL
    pnl_color = '#4CAF50' if trade['pnl'] >= 0 else '#f44336'
    pnl_sign = '+' if trade['pnl'] >= 0 else ''
    ax.text(0.68, row_y, f"{pnl_sign}{trade['pnl']:.2f}", transform=ax.transAxes, 
            fontsize=11, color=pnl_color, ha='center', fontweight='bold')
    
    # Trigger
    trigger_color = '#2196F3' if 'vwap' in trade['trigger'] else '#9C27B0'
    ax.text(0.80, row_y, trade['trigger'], transform=ax.transAxes, 
            fontsize=10, color=trigger_color, ha='center')
    
    # Time in market
    ax.text(0.92, row_y, f"{trade['entry_time']}–{trade['exit_time']}", transform=ax.transAxes, 
            fontsize=10, color='#a0a0a0', ha='center')
    
    row_y -= 0.08

# Summary box
summary_y = row_y - 0.05
ax.add_patch(mpatches.FancyBboxPatch((0.15, summary_y - 0.12), 0.70, 0.10,
                                    boxstyle="round,pad=0.01", 
                                    facecolor='#2a2a4e', edgecolor='#404060',
                                    transform=ax.transAxes))

ax.text(0.5, summary_y - 0.07, 
        '💡 Summary: 3 trades, all flat-to-negative. Liquidity filters blocked early entries. '
        '4141 peaked at 21.19 (+1.2%) but sold at breakeven. No positions held >2h.',
        transform=ax.transAxes, fontsize=10, color='#b0b0b0', 
        ha='center', va='center', style='italic')

# Footer
ax.text(0.5, 0.02, 'Generated by Mino 🪼 | Data: TASI Execution Bot | TASI Market: Sun–Thu 10:00–15:00 KSA',
        transform=ax.transAxes, fontsize=9, color='#606080', ha='center')

# Remove axes
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.axis('off')

# Save
plt.tight_layout()
plt.savefig('/home/mino/tasi-exec/chart_memo_2026-06-23.png', 
            dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
print("✅ Chart saved: /home/mino/tasi-exec/chart_memo_2026-06-23.png")
